export type Photo = {
  id: string;
  slug: string;
  title: string;
  description?: string;
  imageUrl: string;
  thumbnailUrl: string;
  width: number;
  height: number;
  location: string;
  city: string;
  country: string;
  takenAtLabel: string;
  sortDate: string;
  sortOrder: number;
  tags: string[];
};

/*
 * To add a new photo:
 * 1. Convert the original image to JPG or WebP.
 * 2. Put it under public/photos/city-name/photo-name.jpg.
 * 3. Add a new object to this array.
 * 4. Use imageUrl and thumbnailUrl paths starting with /photos/.
 *
 * No photo component changes are needed when adding a city or photo.
 */
const photoEntries: Photo[] = [
  {
    id: "athens-01",
    slug: "athens-01",
    title: "Athens I",
    description: "A photo I took in Athens.",
    imageUrl: "/photos/athens/athens-01.jpg",
    thumbnailUrl: "/photos/athens/athens-01.jpg",
    width: 2268,
    height: 4032,
    location: "Athens, Greece",
    city: "Athens",
    country: "Greece",
    takenAtLabel: "March, 2026",
    sortDate: "2026-03",
    sortOrder: 1,
    tags: ["athens", "greece", "travel"],
  },
  {
    id: "athens-02",
    slug: "athens-02",
    title: "Athens II",
    description: "A photo I took in Athens.",
    imageUrl: "/photos/athens/athens-02.jpg",
    thumbnailUrl: "/photos/athens/athens-02.jpg",
    width: 2268,
    height: 4032,
    location: "Athens, Greece",
    city: "Athens",
    country: "Greece",
    takenAtLabel: "March, 2026",
    sortDate: "2026-03",
    sortOrder: 2,
    tags: ["athens", "greece", "travel"],
  },
  {
    id: "athens-03",
    slug: "athens-03",
    title: "Athens III",
    description: "A photo I took in Athens.",
    imageUrl: "/photos/athens/athens-03.jpg",
    thumbnailUrl: "/photos/athens/athens-03.jpg",
    width: 2268,
    height: 4032,
    location: "Athens, Greece",
    city: "Athens",
    country: "Greece",
    takenAtLabel: "March, 2026",
    sortDate: "2026-03",
    sortOrder: 3,
    tags: ["athens", "greece", "travel"],
  },
  {
    id: "stockholm-01",
    slug: "stockholm-01",
    title: "Stockholm I",
    description: "A photo I took in Stockholm.",
    imageUrl: "/photos/stockholm/stockholm-01.jpg",
    thumbnailUrl: "/photos/stockholm/stockholm-01.jpg",
    width: 1237,
    height: 2200,
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    takenAtLabel: "September, 2026",
    sortDate: "2026-09",
    sortOrder: 1,
    tags: ["stockholm", "sweden", "travel"],
  },
  {
    id: "stockholm-02",
    slug: "stockholm-02",
    title: "Stockholm II",
    description: "A photo I took in Stockholm.",
    imageUrl: "/photos/stockholm/stockholm-02.jpg",
    thumbnailUrl: "/photos/stockholm/stockholm-02.jpg",
    width: 1237,
    height: 2200,
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    takenAtLabel: "September, 2026",
    sortDate: "2026-09",
    sortOrder: 2,
    tags: ["stockholm", "sweden", "travel"],
  },
  {
    id: "stockholm-03",
    slug: "stockholm-03",
    title: "Stockholm III",
    description: "A photo I took in Stockholm.",
    imageUrl: "/photos/stockholm/stockholm-03.jpg",
    thumbnailUrl: "/photos/stockholm/stockholm-03.jpg",
    width: 1237,
    height: 2200,
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    takenAtLabel: "September, 2026",
    sortDate: "2026-09",
    sortOrder: 3,
    tags: ["stockholm", "sweden", "travel"],
  },
  {
    id: "stockholm-04",
    slug: "stockholm-04",
    title: "Stockholm IV",
    description: "A photo I took in Stockholm.",
    imageUrl: "/photos/stockholm/stockholm-04.jpg",
    thumbnailUrl: "/photos/stockholm/stockholm-04.jpg",
    width: 1237,
    height: 2200,
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    takenAtLabel: "September, 2026",
    sortDate: "2026-09",
    sortOrder: 4,
    tags: ["stockholm", "sweden", "travel"],
  },
  {
    id: "stockholm-05",
    slug: "stockholm-05",
    title: "Stockholm V",
    description: "A photo I took in Stockholm.",
    imageUrl: "/photos/stockholm/stockholm-05.jpg",
    thumbnailUrl: "/photos/stockholm/stockholm-05.jpg",
    width: 1237,
    height: 2200,
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    takenAtLabel: "September, 2026",
    sortDate: "2026-09",
    sortOrder: 5,
    tags: ["stockholm", "sweden", "travel"],
  },
  {
    id: "stockholm-06",
    slug: "stockholm-06",
    title: "Stockholm VI",
    description: "A photo I took in Stockholm.",
    imageUrl: "/photos/stockholm/stockholm-06.jpg",
    thumbnailUrl: "/photos/stockholm/stockholm-06.jpg",
    width: 1237,
    height: 2200,
    location: "Stockholm, Sweden",
    city: "Stockholm",
    country: "Sweden",
    takenAtLabel: "September, 2026",
    sortDate: "2026-09",
    sortOrder: 6,
    tags: ["stockholm", "sweden", "travel"],
  },
  {
    id: "bilbao-01",
    slug: "bilbao-01",
    title: "Bilbao 01",
    description: "Photo from Bilbao, Spain.",
    imageUrl: "/photos/bilbao/bilbao-01.jpg",
    thumbnailUrl: "/photos/bilbao/bilbao-01.jpg",
    width: 1237,
    height: 2200,
    location: "Bilbao, Spain",
    city: "Bilbao",
    country: "Spain",
    takenAtLabel: "February, 2026",
    sortDate: "2026-02",
    sortOrder: 1,
    tags: ["bilbao", "spain", "travel", "city"],
  },
  {
    id: "bilbao-02",
    slug: "bilbao-02",
    title: "Bilbao 02",
    description: "Photo from Bilbao, Spain.",
    imageUrl: "/photos/bilbao/bilbao-02.jpg",
    thumbnailUrl: "/photos/bilbao/bilbao-02.jpg",
    width: 1237,
    height: 2200,
    location: "Bilbao, Spain",
    city: "Bilbao",
    country: "Spain",
    takenAtLabel: "February, 2026",
    sortDate: "2026-02",
    sortOrder: 2,
    tags: ["bilbao", "spain", "travel", "city"],
  },
  {
    id: "bilbao-03",
    slug: "bilbao-03",
    title: "Bilbao 03",
    description: "Photo from Bilbao, Spain.",
    imageUrl: "/photos/bilbao/bilbao-03.jpg",
    thumbnailUrl: "/photos/bilbao/bilbao-03.jpg",
    width: 1237,
    height: 2200,
    location: "Bilbao, Spain",
    city: "Bilbao",
    country: "Spain",
    takenAtLabel: "February, 2026",
    sortDate: "2026-02",
    sortOrder: 3,
    tags: ["bilbao", "spain", "travel", "city"],
  },
];

export const photos = [...photoEntries].sort(
  (a, b) => a.sortDate.localeCompare(b.sortDate) || a.sortOrder - b.sortOrder,
);
